name: Run Test and Report Coverage

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    # paths:
    #   - "**.dart"
    #   - "pubspec.yaml"

permissions:
  contents: write
  pull-requests: write

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Run Test
        run: flutter test --coverage
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: LCOV Summary Reporter
        uses: pre-history/lcov-summary-action@lcov-summary-action-v0.4.1
        with:
          lcov-file: ./coverage/lcov.info
          comment-on-pr: true
