name: Run Test and Report Coverage

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "**.dart"
      - "pubspec.yaml"

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Run Test
        run: flutter test --coverage
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage for Pull Request
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
